name: Bug report
description: File a bug reports regarding the application.
labels: ['bug']
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out an issue, this template is meant for any issues related to the Homer-UI
- type: textarea
  id: description
  attributes:
    label: Describe the bug.
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  id: repro
  attributes: 
    label: Reproduction
    description: |
      How can this bug be reproduced?
      Provide screenshots or recordings if possible
    placeholder: |
      1. Switch on...
      2. Press button '....'
      3. Wait for the moon phase
      4. It burns
  validations:
    required: true
- type: input
  id: app-version
  attributes:
    label: Application version
    description: Specify version of application 
  validations:
    required: true
- type: input
  id: browser-version
  attributes:
    label: Browser version
    description: Specify version of your browser 
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: Attach your debug logs here
    render: Text
    # Avoid rendering as Markdown here.
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: Let us know if you have anything else to share.
